// <auto-generated />
using System;
using BikeTracking.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeTracking.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BikeTrackingDbContext))]
    partial class BikeTrackingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.AuthAttemptStateEntity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveWrongCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("DelayUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessfulAuthUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastWrongAttemptUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("AuthAttemptStates", (string)null);
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.Entities.GasPriceLookupEntity", b =>
                {
                    b.Property<int>("GasPriceLookupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EiaPeriodDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PriceDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerGallon")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("GasPriceLookupId");

                    b.HasIndex("PriceDate")
                        .IsUnique();

                    b.ToTable("GasPriceLookups", (string)null);
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.Entities.RideEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CloudCoverPercent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GasPricePerGallon")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Miles")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrecipitationType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelativeHumidityPercent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RideDateTimeLocal")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RideMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RiderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SnapshotAverageCarMpg")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SnapshotMileageRateCents")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SnapshotOilChangePrice")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SnapshotYearlyGoalMiles")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<bool>("WeatherUserOverridden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int?>("WindDirectionDeg")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("WindSpeedMph")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RiderId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Rides_RiderId_CreatedAtUtc_Desc");

                    b.ToTable("Rides", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rides_Miles_GreaterThanZero", "CAST(\"Miles\" AS REAL) > 0 AND CAST(\"Miles\" AS REAL) <= 200");

                            t.HasCheckConstraint("CK_Rides_RideMinutes_GreaterThanZero", "\"RideMinutes\" IS NULL OR \"RideMinutes\" > 0");

                            t.HasCheckConstraint("CK_Rides_SnapshotAverageCarMpg_Positive", "\"SnapshotAverageCarMpg\" IS NULL OR CAST(\"SnapshotAverageCarMpg\" AS REAL) > 0");

                            t.HasCheckConstraint("CK_Rides_SnapshotMileageRateCents_Positive", "\"SnapshotMileageRateCents\" IS NULL OR CAST(\"SnapshotMileageRateCents\" AS REAL) > 0");

                            t.HasCheckConstraint("CK_Rides_SnapshotOilChangePrice_Positive", "\"SnapshotOilChangePrice\" IS NULL OR CAST(\"SnapshotOilChangePrice\" AS REAL) > 0");

                            t.HasCheckConstraint("CK_Rides_SnapshotYearlyGoalMiles_Positive", "\"SnapshotYearlyGoalMiles\" IS NULL OR CAST(\"SnapshotYearlyGoalMiles\" AS REAL) > 0");
                        });
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.Entities.UserSettingsEntity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AverageCarMpg")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DashboardGallonsAvoidedEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("DashboardGoalProgressEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationLabel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MileageRateCents")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OilChangePrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("YearlyGoalMiles")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserSettings_AverageCarMpg_Positive", "\"AverageCarMpg\" IS NULL OR CAST(\"AverageCarMpg\" AS REAL) > 0");

                            t.HasCheckConstraint("CK_UserSettings_Latitude_Range", "\"Latitude\" IS NULL OR (CAST(\"Latitude\" AS REAL) >= -90 AND CAST(\"Latitude\" AS REAL) <= 90)");

                            t.HasCheckConstraint("CK_UserSettings_Longitude_Range", "\"Longitude\" IS NULL OR (CAST(\"Longitude\" AS REAL) >= -180 AND CAST(\"Longitude\" AS REAL) <= 180)");

                            t.HasCheckConstraint("CK_UserSettings_MileageRateCents_Positive", "\"MileageRateCents\" IS NULL OR CAST(\"MileageRateCents\" AS REAL) > 0");

                            t.HasCheckConstraint("CK_UserSettings_OilChangePrice_Positive", "\"OilChangePrice\" IS NULL OR CAST(\"OilChangePrice\" AS REAL) > 0");

                            t.HasCheckConstraint("CK_UserSettings_YearlyGoalMiles_Positive", "\"YearlyGoalMiles\" IS NULL OR CAST(\"YearlyGoalMiles\" AS REAL) > 0");
                        });
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.Entities.WeatherLookupEntity", b =>
                {
                    b.Property<int>("WeatherLookupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CloudCoverPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LatitudeRounded")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LongitudeRounded")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LookupHourUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrecipitationType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelativeHumidityPercent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WindDirectionDeg")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("WindSpeedMph")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("WeatherLookupId");

                    b.HasIndex("LookupHourUtc", "LatitudeRounded", "LongitudeRounded")
                        .IsUnique();

                    b.ToTable("WeatherLookups", (string)null);
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.OutboxEventEntity", b =>
                {
                    b.Property<long>("OutboxEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AggregateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("OutboxEventId");

                    b.HasIndex("AggregateType", "AggregateId");

                    b.HasIndex("PublishedAtUtc", "NextAttemptUtc");

                    b.ToTable("OutboxEvents", (string)null);
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.UserCredentialEntity", b =>
                {
                    b.Property<long>("UserCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CredentialVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("IterationCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PinHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PinSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserCredentialId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCredentials", (string)null);
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.UserEntity", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.AuthAttemptStateEntity", b =>
                {
                    b.HasOne("BikeTracking.Api.Infrastructure.Persistence.UserEntity", "User")
                        .WithOne("AuthAttemptState")
                        .HasForeignKey("BikeTracking.Api.Infrastructure.Persistence.AuthAttemptStateEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.Entities.RideEntity", b =>
                {
                    b.HasOne("BikeTracking.Api.Infrastructure.Persistence.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.Entities.UserSettingsEntity", b =>
                {
                    b.HasOne("BikeTracking.Api.Infrastructure.Persistence.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.UserCredentialEntity", b =>
                {
                    b.HasOne("BikeTracking.Api.Infrastructure.Persistence.UserEntity", "User")
                        .WithOne("Credential")
                        .HasForeignKey("BikeTracking.Api.Infrastructure.Persistence.UserCredentialEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.UserEntity", b =>
                {
                    b.Navigation("AuthAttemptState");

                    b.Navigation("Credential");
                });
#pragma warning restore 612, 618
        }
    }
}
