// <auto-generated />
using System;
using BikeTracking.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeTracking.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BikeTrackingDbContext))]
    partial class BikeTrackingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.AuthAttemptStateEntity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveWrongCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("DelayUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessfulAuthUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastWrongAttemptUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("AuthAttemptStates", (string)null);
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.Entities.RideEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Miles")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RideDateTimeLocal")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RideMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RiderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RiderId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Rides_RiderId_CreatedAtUtc_Desc");

                    b.ToTable("Rides", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rides_Miles_GreaterThanZero", "\"Miles\" > 0");

                            t.HasCheckConstraint("CK_Rides_RideMinutes_GreaterThanZero", "\"RideMinutes\" IS NULL OR \"RideMinutes\" > 0");
                        });
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.OutboxEventEntity", b =>
                {
                    b.Property<long>("OutboxEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AggregateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventPayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("OutboxEventId");

                    b.HasIndex("AggregateType", "AggregateId");

                    b.HasIndex("PublishedAtUtc", "NextAttemptUtc");

                    b.ToTable("OutboxEvents", (string)null);
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.UserCredentialEntity", b =>
                {
                    b.Property<long>("UserCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CredentialVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("IterationCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PinHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PinSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserCredentialId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCredentials", (string)null);
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.UserEntity", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.AuthAttemptStateEntity", b =>
                {
                    b.HasOne("BikeTracking.Api.Infrastructure.Persistence.UserEntity", "User")
                        .WithOne("AuthAttemptState")
                        .HasForeignKey("BikeTracking.Api.Infrastructure.Persistence.AuthAttemptStateEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.Entities.RideEntity", b =>
                {
                    b.HasOne("BikeTracking.Api.Infrastructure.Persistence.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.UserCredentialEntity", b =>
                {
                    b.HasOne("BikeTracking.Api.Infrastructure.Persistence.UserEntity", "User")
                        .WithOne("Credential")
                        .HasForeignKey("BikeTracking.Api.Infrastructure.Persistence.UserCredentialEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeTracking.Api.Infrastructure.Persistence.UserEntity", b =>
                {
                    b.Navigation("AuthAttemptState");

                    b.Navigation("Credential");
                });
#pragma warning restore 612, 618
        }
    }
}
